services:
  tapsegnn: 
    build: 
      context: . 
      args: 
        PYTHON_VERSION: 3.11.11 
    image: tapsegnn-image 
    container_name: tapsegnn-container 
    working_dir: /tapsegnn 
    environment:
      - PYTHONUNBUFFERED=1
      - MATPLOTLIB_BACKEND=Agg
    command: ["python", "src/main.py"] 

  tapsegnn-dev:
    build: 
      context: . 
      args: 
        PYTHON_VERSION: 3.11.11 
    image: tapsegnn-image 
    container_name: tapsegnn-container\
    profiles: ["dev"]
    stdin_open: true 
    tty: true 
    volumes:
      - ./src:/tapsegnn/src 
      - ./utils:/tapsegnn/utils 
      - ./notebooks:/tapsegnn/notebooks 
      - ./config:/tapsegnn/config
      - ./results:/tapsegnn/results
    working_dir: /tapsegnn 
    environment: 
      - PYTHONUNBUFFERED=1
      - MATPLOTLIB_BACKEND=Agg
    command: ["/bin/bash"]



  


