version: '3.8'

services:
  


# version: '3.8'

# services:
#   tapsegnn:
#     build:
#       context: .
#       args:
#         PYTHON_VERSION: 3.11.11
#     image: test-image
#     container_name: tapsegnn-container
#     stdin_open: true
#     tty: true
#     volumes:
#       - type: bind
#         source: .
#         target: /src
#     working_dir: /tapsegnn
#     environment:
#       - PYTHONUNBUFFERED=1
#       - MATPLOTLIB_BACKEND=Agg
#     # Uncomment the line below if you want to run main.py automatically
#     # command: ["python", "main.py"]
#     # Comment out the line below if you want to run main.py automatically
#     command: ["/bin/bash"]